name: simple ci pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: setup nodejs
          uses: actions/setup-node@v4
          with:
            node-version: "20"
        - name: install dep
          uses: npm install
        - name: run tests
          uses: npm test -- --passWithNoTests
        - name: build application
          uses: npm run build --if-present